const products = [
  {
    image: "./images/product-1.jpg",
    title: "Nike Repel Miler",
    type: "Dress",
    price: 120.5,
    discount: 0,
    badge: "",
  },
  {
    image: "./images/product-2.jpg",
    title: "Nike Sportswear Futura Luxe",
    type: "Glasses",
    price: 160.0,
    discount: 0,
    badge: "",
  },
  {
    image: "./images/product-3.jpg",
    title: "Adicolor Classics Joggers",
    type: "Dress",
    price: 63.85,
    discount: 0,
    badge: "HOT",
  },
  {
    image: "./images/product-4.jpg",
    title: "Nike Sportswear Futura Luxe",
    type: "Bag",
    price: 130.0,
    discount: 0,
    badge: "",
  },
  {
    image: "./images/product-5.jpg",
    title: "Geometric print Scarf",
    type: "scarf",
    price: 53.0,
    discount: 0,
    badge: "",
  },
  {
    image: "./images/product-6.jpg",
    title: "Nike Air Zoom Pegasus",
    type: "Shoe",
    price: 220.0,
    discount: 198.0,
    badge: "SALE",
  },
  {
    image: "./images/product-7.jpg",
    title: "Basic Dress Green",
    type: "Dress",
    price: 236.0,
    discount: 0,
    badge: "",
  },
  {
    image: "./images/product-8.jpg",
    title: "Yellow Reserved Hoodie",
    type: "Dress",
    price: 364.0,
    discount: 155.0,
    badge: "SALE",
  },
];
export default products;
